name: CI

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  checks:
    name: Nix checks (${{ matrix.os }})
    permissions:
      contents: read
      # For flakehub-cache-action
      id-token: write
    strategy:
      matrix:
        os:
          - UbuntuLatest32Cores128G
          - UbuntuLatest32Cores128GArm
          - macos-latest-xlarge
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Build, test, clippy, rustfmt
        run: nix flake check -L
      - name: Check editorconfig conformance
        run: nix develop --command editorconfig-checker

  cargo-deny:
    name: Advisories, licenses, sources
    runs-on: UbuntuLatest32Cores128G
    permissions:
      contents: read
      # For flakehub-cache-action
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix develop --command cargo deny check

  flake-checker:
    name: Check flake.lock health
    runs-on: UbuntuLatest32Cores128G
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/flake-checker-action@main

  success:
    runs-on: ubuntu-latest
    needs:
      - checks
      - cargo-deny
      - flake-checker
    if: ${{ always() }}
    steps:
      - run: "true"
      - run: |
          echo "A dependent in the build matrix failed."
          exit 1
        if: |
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled')
